# Generated by Django 5.2 on 2025-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_name', models.CharField(max_length=20)),
                ('eve_discription', models.TextField()),
                ('eve_image', models.ImageField(upload_to='about_images/')),
            ],
        ),
    ]
