# Generated by Django 5.2 on 2025-04-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='eve_image',
            new_name='image',
        ),
    ]
