# Generated by Django 5.2 on 2025-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_eve_image_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='eve_name',
            field=models.CharField(max_length=100),
        ),
    ]
