# Generated by Django 5.2 on 2025-04-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_botresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.CharField(max_length=255, unique=True)),
                ('bot_reply', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BotResponse',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
