# Generated by Django 5.2 on 2025-04-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='need_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='transport_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
