# Generated by Django 5.2 on 2025-04-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_booking_location_alter_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transport_Price',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(default='Unknown', max_length=300),
        ),
    ]
