# Generated by Django 5.2 on 2025-04-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_booking_transport_price_alter_booking_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('event', 'Event'), ('catering', 'Catering'), ('other', 'Other')], default='event', max_length=50),
        ),
    ]
