# Generated by Django 5.2 on 2025-04-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='name',
            new_name='for_booking',
        ),
        migrations.AddField(
            model_name='venue',
            name='resistance_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
