# Generated by Django 5.2 on 2025-04-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_name_venue_for_booking_venue_resistance_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='resistance_name',
            new_name='facilitator',
        ),
    ]
