# Generated by Django 5.2 on 2025-04-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_resistance_name_venue_facilitator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('hall', 'Hall'), ('hotel', 'Hotel'), ('lawn', 'Lawn'), ('lawn & hotel', 'Lawn & Hotel')], max_length=100),
        ),
    ]
